import { useSearchParams } from 'react-router-dom'
import { useState } from 'react'
import { FileSearch, Shield, Bug, BookOpen, TestTube2, Sparkles } from 'lucide-react'
import RepoForm from '../components/RepoForm'
import ProgressTimeline from '../components/ProgressTimeline'
import ReportCard from '../components/ReportCard'
import { useReview } from '../hooks/useReview'
const actions = [{label:'Analyze', icon:FileSearch, endpoint:'/analyze'}, {label:'Summary', icon:BookOpen, endpoint:'/summary'}, {label:'Bugs', icon:Bug, endpoint:'/bugs'}, {label:'Security', icon:Shield, endpoint:'/security'}, {label:'Tests', icon:TestTube2, endpoint:'/tests'}, {label:'README', icon:BookOpen, endpoint:'/readme'}]
export default function Dashboard() { const [params] = useSearchParams(); const [repo, setRepo] = useState(params.get('repo') || ''); const {reports, progress, loading, error, run, improve} = useReview(); const performImprove = url => { setRepo(url); improve(url) }; return <div className="mx-auto max-w-7xl px-6 pb-14 pt-8"><div className="mb-8"><p className="text-sm text-violet-300">Repository command center</p><h1 className="mt-1 text-3xl font-bold">Code review with a pulse.</h1><p className="mt-2 text-slate-400">Run the full orchestrated diagnosis or ask a focused question.</p></div><RepoForm onSubmit={performImprove} loading={loading} initialUrl={repo} /><div className="mt-4 flex flex-wrap gap-2">{actions.map(({label,icon:Icon,endpoint}) => <button key={label} disabled={!repo || loading} onClick={() => run(endpoint, repo)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-sm text-slate-300 hover:bg-white/5 disabled:cursor-not-allowed disabled:opacity-40"><Icon size={15}/>{label}</button>)}<button disabled={!repo || loading} onClick={() => improve(repo)} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-3 py-2 text-sm font-medium hover:bg-violet-500 disabled:opacity-40"><Sparkles size={15}/>Improve everything</button></div>{error && <div role="alert" className="mt-5 rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-200">{error}</div>}<div className="mt-7 grid gap-6 lg:grid-cols-[280px_1fr]"><ProgressTimeline events={progress}/><section className="space-y-5">{reports.length ? reports.map((report, index) => <ReportCard key={`${report.title}-${index}`} report={report}/>) : <div className="glass grid min-h-80 place-items-center rounded-2xl p-8 text-center text-slate-400"><div><FileSearch className="mx-auto mb-3 text-violet-400" size={32}/><p className="font-medium text-slate-200">Ready to examine a repository</p><p className="mt-1 text-sm">Paste a GitHub URL above, then choose a focused review or run the full pipeline.</p></div></div>}</section></div></div> }
